config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  resources :categories, except: [:destroy]
  
  get 'signup', to: 'users#new'
  
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new' # login form
  post 'login', to: 'sessions#create' # submission login form
  delete 'logout', to: 'sessions#destroy'
  

end

app/models/article.rb
class Article < ActiveRecord::Base
    
  has_many :article_categories
  has_many :categories, through: :article_categories
    
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10 }
  validates :user_id, presence: true
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 before_action :set_artikel, only: [:edit, :update, :show, :destroy]
 # before_action :require_user, except: [:index, :show]
 before_action :require_same_user, only: [:edit, :update, :destroy]
   
   def destroy
        # replaced by set_artikel before action --> @article = Article.find(params[:id])
      @article.destroy
      flash[:danger] = "Artikel verwijderd!!"
        # redirect_to articles_path
      respond_to do |wants|
        wants.html { redirect_to(articles_url) }
        wants.xml  { head :ok }
      end
   end
   
   def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
   end
   
   def new
    @article = Article.new   
   end
   
   def edit
    # replaced by set_artikel before action --> @article = Article.find(params[:id])
   end
   
   def update
    # replaced by set_artikel before action --> @article = Article.find(params[:id])
    if @article.update(article_params)
     flash[:success] = "Artikel succesvol aangepast!"
     redirect_to article_path(@article)
    else
     render 'edit'
    end
   end
   
   def create
    # debugger
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
     flash[:success] = "Artikel succesvol aangemaakt"
     redirect_to article_path(@article)
    else
     render 'new'
     
    end
   end
   
   def show
    # replaced by set_artikel before action --> @article = Article.find(params[:id])
   end
   
   
  private
  
  def set_artikel
  @article = Article.find(params[:id])
  end
 
  def article_params
   params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
     if current_user != @article.user and !current_user.admin?
        flash[:danger] = "U kunt alleen uw eigen artikelen aanpassen of verwijderen!"
        redirect_to article_path
     end
  end
  
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
    <div class="row well well-lg col-xs-8 col-xs-offset-2">
        <div class="artikel-titel">
            <%= link_to article.title, article_path(article) %>
        </div>
        <div class="artikel-body">
        <%= truncate(article.description, lenght: 100) %>
            <div class="article-meta-details">
            <small>
                Created by: <%= article.user.username if article.user %>,
                <%= time_ago_in_words(article.created_at) %> ago,
                last updated: <%= time_ago_in_words(article.updated_at) %> ago
            </small>
            </div>
        </div>
        
        <% if article.categories.any? %>
          <p>Categorieën: <%= render article.categories %></p>
        <% end %>
        
        <% if logged_in? && (current_user == article.user or current_user.admin?) %>
            <div class="article-actions">
                <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-primary btn-xs" %>
                <%= link_to "Delete this article", article_path(article), method: :delete, data: { confirm: "Weet u het zeker? OK=delete"}, 
                                                class: "btn btn-danger btn-xs" %>
            </div>
        <% end %>
    </div>
    <% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
    <div class="col-xs-12">
        
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
            <div class="col-sm-2 control-label">
                <%= f.label :title %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :title, class: "form-control", placeholder: "titel van het artikel", autofocus: true %>
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-sm-2 control-label">
                <%= f.label :description %>
            </div>
            <div class="col-sm-8">
                <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "tekst van het artikel (max. 300 tekens)" %>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                  <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
                <% end %>
            </div>
        </div> 
        <div class="form-group">
            <div class="row">
              <div class="col-sm-offset-2 col-sm-8">
                  <%= f.submit class: "btn btn-primary btn-lg" %>
              </div>
            </div>
        </div>
        <% end %>
    </div>
    <div class="col-xs-4 col-xs-offset-4">
        [ <%= link_to "cancel en terug naar artikelen overzicht", articles_path %> ]
    </div>

</div>

app/views/articles/edit.html.erb
<h1 align="center">This is the edit-page of article nr: <%= @article.id %></h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all artikelen:</h1>

<div align="center">
    <%= will_paginate %>
</div>
    
<%= render 'article', obj: @articles %>

<div align="center">
    <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an artikel:</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align=center>Titel: <%= @article.title %></h2>
    <div class="well col-xs-8 col-xs-offset-2">
        <% if @article.user %>
            <ul class="userlist">
            <div class="row" align="center">
                <div class="col-md-4 col-md-offset-4">
                    <li>Created by:</li>
                    <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
                    <li class="article-title"><%= link_to @article.user.username, user_path(@article.user) %></li>
                    <li><small><%= pluralize(@article.user.articles.count, "artikel") if @article.user.articles %></small></li>
                </div>
            </div>
            </ul>
        <% end %>
    <h4 class="center omschrijving"><strong>Omschrijving/Inhoud:</strong></h4>
    <hr>
    <%= simple_format(@article.description) %>
    
    <% if @article.categories.any? %>
      <p>Categorieën: <%= render @article.categories %></p>
    <% end %>
    
    <div class="article-actions">
        <% if logged_in? && (current_user == @article.user or current_user.admin?) %>
            <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-primary btn-xs" %>
            <%= link_to "Delete this article", article_path(@article), method: :delete, data: { confirm: "Weet u het zeker? OK=delete"}, 
                                                class: "btn btn-danger btn-xs" %>
        <% end %>
        <%= link_to "Bekijk alle artikelen", articles_path, class: "btn btn-success btn-xs" %>
    </div>
</div>