config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  resources :categories, except: [:destroy]
  
  get 'signup', to: 'users#new'
  
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new' # login form
  post 'login', to: 'sessions#create' # submission login form
  delete 'logout', to: 'sessions#destroy'
  

end

app/models/category.rb
class Category < ActiveRecord::Base
    
  has_many :article_categories
  has_many :articles, through: :article_categories
    
  validates :name, presence: true
  validates :name, uniqueness: true # wat ook kan: validates_uniqueness_of :name #
  validates :name, :length => { :in => 3..25 }
    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    
    before_action :require_admin, only: [:create, :new, :edit, :update]
    
    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end
    
    def new
        @category = Category.new
    end
    
    def create
        @category = Category.new(category_params)
        if @category.save
                flash[:success] = "Categorie \"#{@category.name}\" is aangemaakt!"
                redirect_to categories_path
            else
                render 'new'
        end
    end
    
    def edit
        @category = Category.find(params[:id])
        
    end
    
    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:success] = "Categorie \"#{@category.name}\" is gewijzigd!"
            redirect_to category_path(@category)
        else
            render 'edit'
        end
        
    end
    
    def show
        @category = Category.find(params[:id])
        @category_articles = @category.articles.paginate(page: params[:page], per_page: 3)
    end
    
    private
    
    def category_params
        params.require(:category).permit(:name)
    end
    
    def require_admin
      if !logged_in? or (logged_in? and !current_user.admin?)
        flash[:danger] = "Alleen admins mogen nieuwe categorieën definiëren of wijzigen!"
        redirect_to root_path
      end
    end

    
    
    
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span> &nbsp;

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<div class="row">
    <div class="col-xs-12">
        
        <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
            <div class="col-sm-2 control-label">
                <%= f.label :naam %>
            </div>
            <div class="col-sm-8">
                <%= f.text_field :name, class: "form-control", autofocus: true %>
            </div>
        </div>
        
        <div class="form-group">
            <div class="row">
              <div class="col-sm-offset-2 col-sm-8">
                  <%= f.submit class: "btn btn-primary btn-lg" %>
              </div>
            </div>
        </div>
        <% end %>
    </div>
    <div class="col-xs-4 col-xs-offset-4">
        [ <%= link_to "cancel en terug naar categorie overzicht", categories_path %> ]
    </div>

</div>

app/views/categories/edit.html.erb
<h1 class="center">Wijzig de naam van categorie "<%= "#{@category.name}" %>"</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Categorie overzicht</h1>
<div align="center">
    <%= will_paginate @categories %>
        <% @categories.each do |category| %>
            <ul class="userlist">
                <div class="row" align="center">
                    <div class="well col-md-4 col-md-offset-4">
                        <li class="artikel-titel">
                            <%= link_to "#{category.name}", category_path(category) %>
                            <p><li><small>
                                (<%= pluralize(category.articles.count, "artikel") if category.articles %>)
                              </small></li></p>
                        </li>
                    </div>
                </div>
            </ul>
        <% end %>
    <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center"> Een nieuwe categorie aanmaken:</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="center">Artikelen met categorie "<%= "#{@category.name}" %>": </h1>

<div class="row" align="center">
  <% if logged_in? && current_user.admin? %>
    <span class=badge>
      <%= link_to "wijzig categorie naam", edit_category_path(@category) %>
    </span>
  <% end %>
</div>

<div align="center">
  <%= will_paginate @category_articles %>
</div>

<%= render 'articles/article', obj: @category_articles %>

<div align="center">
  <%= will_paginate @category_articles %>
</div>