config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  resources :categories, except: [:destroy]
  
  get 'signup', to: 'users#new'
  
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new' # login form
  post 'login', to: 'sessions#create' # submission login form
  delete 'logout', to: 'sessions#destroy'
  

end

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>Copyright &copy; <a href="https://nl.linkedin.com/in/bstraver"  target="_blank">ROR Projects by BGJS</a></small>
        <nav>
            <ul>
                <li><%= link_to "About", about_path %></li>
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
     <% flash.each do |name, msg| %>
        <div class='alert alert-<%= "#{name}" %>'>
        <%#  <a href="#" class="close" data-dismiss="alert">&#215;</a>  geeft het close-kruisje reachts in de message box %>
            <button type="button" class="close" aria-label="Close" data-dismiss="alert">
                 <span aria-hidden="false">&times;</span>
            </button> <%# idem: close kruisje %>
         <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
      <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       
        <li><%= link_to "Artikelen", articles_path %></li>
        <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actie <span class="caret"></span></a>
              <ul class="dropdown-menu">
                
                <li><%= link_to "nieuw artikel", new_article_path %></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          <% end %>
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categoriën <span class="caret"></span></a>
              <ul class="dropdown-menu">
                
                <li><%= link_to "alle categorieën", categories_path %></li>
                  <% Category.all.each do |categorie| %>
                    <li><%= link_to "#{categorie.name}", category_path(categorie) %></li>
                  <% end %>
                  <% if logged_in? and current_user.admin? %>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to "nieuwe categorie", new_category_path %></li>
                  <% end %>
              </ul>
            </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><% if current_user.admin? %>
                  <%= link_to "Log out " + "#{current_user.username.upcase}" + " (admin)", logout_path, method: :delete %>
                <% else %>
                  <%= link_to "Log out " + "#{current_user.username.upcase}" + " (user)", logout_path, method: :delete %>
                <% end %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Uw profiel <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'edit uw profiel', edit_user_path(current_user) %></li>
              <li><%= link_to 'bekijk uw profiel', user_path(current_user) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
            <li><%= link_to 'Log in', login_path %></li>
            <li><%= link_to 'Sign up', signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>
<div class="container">
<%= yield %>
</div>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>